apiVersion: v1
kind: Pod
metadata:
  name: myredis
  namespace: {{ .Values.namespace.Name | default "default" }}
  labels:
    name: myredis
spec:
  containers:
  - name: my-container-pod
    image: redis:alpine3.16
    ports:
    - containerPort: 6379